name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 16
        
      - run: yarn config set registry https://registry.npmmirror.com/
        
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn.lock
          restore-keys: |
            ${{ runner.os }}-yarn-
      
      - run: yarn install
      
      - name: Build/release Electron app
        run: yarn release
        with:
          github_token: ${{ secrets.github_token }}
          